final products = [
  {
    'id': 0,
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Nike',
    'imageUrl': 'assets/images/shoes_1.png',
  },
  {
    'id': 1,
    'title': 'Adidas Shoes',
    'price': 45.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoes_2.png',
  },
  {
    'id': 2,
    'title': 'Puma Shoes',
    'price': 46.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Puma',
    'imageUrl': 'assets/images/shoes_3.png',
  },
  {
    'id': 3,
    'title': 'New Balance Shoes',
    'price': 47.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'New Balance',
    'imageUrl': 'assets/images/shoes_4.png',
  },
  {
    'id': 4,
    'title': 'Men\'s Skechers Shoes',
    'price': 48.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Skechers',
    'imageUrl': 'assets/images/shoes_5.png',
  },
  {
    'id': 5,
    'title': 'Men\'s Skechers Shoes',
    'price': 49.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Skechers',
    'imageUrl': 'assets/images/shoes_6.png',
  },
  {
    'id': 6,
    'title': 'Men\'s Nike Shoes',
    'price': 50.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Nike',
    'imageUrl': 'assets/images/shoes_7.png',
  },
  {
    'id': 7,
    'title': 'Men\'s Nike Shoes',
    'price': 51.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Nike',
    'imageUrl': 'assets/images/shoes_8.png',
  },
  {
    'id': 8,
    'title': 'Men\'s Puma Shoes',
    'price': 52.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Puma',
    'imageUrl': 'assets/images/shoes_9.png',
  },
  {
    'id': 9,
    'title': 'Men\'s Puma Shoes',
    'price': 53.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Puma',
    'imageUrl': 'assets/images/shoes_10.png',
  },
  {
    'id': 10,
    'title': 'Men\'s Adidas Shoes',
    'price': 54.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoes_11.png',
  },
  {
    'id': 11,
    'title': 'Men\'s Adidas Shoes',
    'price': 55.52,
    'sizes': [8, 9, 10, 11, 12],
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoes_12.png',
  },
];
